### ISSUE TITLE
could not set file modification time of 'xxx': permission denied

### ISSUE THREAD

**Issue by LuckyFellow** [ventz/docker-bind#18]
I configured the container to be a secondary authoratative dns server.
When it receives a zone refresh from the master server, the log shows the following message:

`29-Apr-2019 23:09:06.703 zone XXX.YYY/IN: refresh: could not set file modification time of '/var/cache/bind/zones/XXX.YYY.zone': permission denied`

These messages appear only after the container has restarted (the file permissions have been changed by 'entrypoint.sh'.
That means, if I delete all cached zone files and start the container, the messages will never appear, unless the container is restarted and 'entrypoint.sh' executed.

Despite these messages, everything seems to function properly.

Executing the following command inside of the container works as expected.
`su -s /bin/sh named -c 'touch -m /var/cache/bind/zones/XXX.YYY.zone'`

It changes the file's modification time.
Which means to me, there actually is no permission problem.

**Comment by ventz** [comment]
@LuckyFellow Are you using NFS for the volume you are providing that ends up being "/var/cache/bind/"?

It sounds like an NFS / NTP issue potentially.

**Comment by LuckyFellow** [comment]
Negative, it is a local ext4 partition managed with lvm.
Mounted through fstab like this:
```
/dev/mapper/vg1-lvol6 /opt ext4 noatime,nodiratime,rw,nosuid,nodev,exec,auto,nouser,async,errors=remount-ro 0 2
```

The host system is debian 9 with most recent kernel 4.9.0-9-amd64 and Docker version 18.09.5, build e8ff056dbc.
The container ist started using docker-compose and the volumes are added like this:
```
    volumes:
      - /opt/bind/authoritative/secondary/config:/etc/bind
      - /opt/bind/authoritative/secondary/cache:/var/cache/bind

```

The following command enforces the log message:
`docker exec <container_name> rndc refresh <domain_name>`

The moment I change the file owner back to named (uid 100) the command above executes without causing the log message.

**Comment by ventz** [comment]
@LuckyFellow I am running this container in production as a secondary slave with:

```
/docker/sc-bind-slave/etc:/etc/bind
/docker/sc-bind-slave/cache:/var/cache/bind
/docker/sc-bind-slave/log:/var/log/named ventz/bind
```

~Not seeing this issue and I can't seem to re-produce it.~
(actually - I think I was just able to reproduce it)

Running this off a local disk:
```
# cat /etc/fstab
LABEL=VPS	/	ext4	defaults,errors=remount-ro,barrier=0 1 1
```

Can you try creating just a "/docker" folder in your root, and trying it from there?
Can you also try a different system/VM/distro? (eliminating some of the basics)

I am running it on: `18.09.5` (l have another one 18.09.1) with `Ubuntu 16.04 LTS` (currently on: 4.4.0-141-generic). I've been running one of the slaves since Ubuntu 12.04 LTS.

EDIT: Reproduced it on a new VPS. See bellow comment.

**Comment by ventz** [comment]
@LuckyFellow Ok, I think I know what's causing it. Try the latest push (also tag: 9.12.4_p1-r1-fix1)

BEFORE you upgrade (unless you use watchtower ;)), do a: `docker exec -it $container` and check your `ls -alh /var/cache` -- see if `bind` is owned by `root:named` instead of `named:named`

If you look at the "BIND suggested directories and owners/groups" for ubuntu/debian vs rhel/centos, you will see that they are quite different. Mentioning this because a while back I tried making alpine follow the recommended "BIND" one (I don't remember now if RHEL or Debian implement the "truer" one), only to realize that it can't because of some of the pre-created dir/ownership assumptions that are built-in. I think the left-over caused the issue.

I believe the latest version should fix it for you.

If for some reason it doesn't - If you started "fresh" (given it's a slave - you can blow away the zones and re-sync without issues) -- that will fix it. Again, if it doesn't, the alternative other part to make sure is the volume you are mounting is chown by UID 100 and GID 101.

Please let me know if this fixes it.

Thanks.

**Comment by LuckyFellow** [comment]
@ventz thank you very much, your fix fixed it!

**Comment by ventz** [comment]
@LuckyFellow Awesome! Thanks for pointing this out. It was one of those edge cases where if you had ever used the container before, the data was "tagged" correctly, and only new zones or a NEW deployment picked it up!
