### ISSUE TITLE
Alpine 3.10 & BIND 9.14.3 now current

### ISSUE THREAD

**Issue by ikluft** [ventz/docker-bind#20]
FYI... you probably want to know about this. [Alpine 3.10](https://alpinelinux.org/posts/Alpine-3.10.0-released.html) is now current, with the [BIND 9.14.3-r0](https://pkgs.alpinelinux.org/package/v3.10/main/x86_64/bind) package. Also, the commit from 2 days ago for #19/CVE-2019-6471 fix is listed on GitHub with a red "x" error - it doesn't show me what the error was. It didn't get automatically posted to Docker Hub.

**Comment by ventz** [comment]
@ikluft Thanks for catching this!

This is where using `:latest` for a docker image can bite you when the build server is not doing regular docker image pulls :)
I added it to watchtower so that it will update in the future as soon as alpine publishes an updated image.

It looks like Alpine 3.10 has removed `rndc-config` from the default `bind` package, and has instead pushed it to `bind-tools`. This was causing the auto-build to break. Also, after updating it, it looks like rndc-config no longer supports `-r` for specifying `/dev/random`.

Should be fixed now (6de0c62). Credited you with the commit. Also pushed out a tag `9.14.3-r0`

**Comment by ikluft** [comment]
Thanks for the prompt fix and the kind words! I verified it works here. Closing the issue...
